### ISSUE TITLE
Instance Model Completeness and Consistency with Literature

### ISSUE THREAD

**Issue by sayarinm** [sayarinm/3dfimSRSReview#5]
**(IM2 in Section 4.2.4 in SRS)**

Please read Instance Model IM2 and the paragraph below it and let us know if the symbols we are using match the ones from the literature, if the inputs and the output are deﬁned correctly and whether the description is complete and unambiguous. 

:star: 3C.Consistency.3.1 and 3C.Completeness.1 and Unambiguous.2

**Comment by inglis-dl** [comment]
I am not familiar with fMRI enough to comment.
